// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PolvorApp.FederationCatalog.Persistence;

#nullable disable

namespace PolvorApp.FederationCatalog.Persistence.Migrations
{
    [DbContext(typeof(FederationCatalogDbContext))]
    [Migration("20260930182509_InitialCatalog")]
    partial class InitialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PolvorApp.FederationCatalog.Assignments.FiringChiefAssignment", b =>
                {
                    b.Property<Guid>("ComparsaId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparsa_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.HasKey("ComparsaId", "UserId")
                        .HasName("pk_firing_chief_assignments");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_firing_chief_assignments_user_id");

                    b.ToTable("firing_chief_assignments", "catalog");
                });

            modelBuilder.Entity("PolvorApp.FederationCatalog.Comparsas.Comparsa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("name_key")
                        .HasComputedColumnSql("lower(name)", true);

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("side");

                    b.HasKey("Id")
                        .HasName("pk_comparsas");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasDatabaseName("ix_comparsas_name_key");

                    b.ToTable("comparsas", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_comparsas_name_not_blank", "btrim(name) <> ''");

                            t.HasCheckConstraint("ck_comparsas_side", "side IN ('MOORISH', 'CHRISTIAN')");
                        });
                });

            modelBuilder.Entity("PolvorApp.FederationCatalog.WeaponModels.WeaponModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Handedness")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("handedness");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<string>("LabelKey")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("label_key")
                        .HasComputedColumnSql("lower(label)", true);

                    b.Property<bool>("Rentable")
                        .HasColumnType("boolean")
                        .HasColumnName("rentable");

                    b.Property<string>("Side")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("side");

                    b.Property<string>("Size")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("size");

                    b.HasKey("Id")
                        .HasName("pk_weapon_models");

                    b.HasIndex("LabelKey")
                        .IsUnique()
                        .HasDatabaseName("ix_weapon_models_label_key");

                    b.HasIndex("Kind", "Side", "Handedness", "Size")
                        .IsUnique()
                        .HasDatabaseName("ix_weapon_models_combination")
                        .HasFilter("kind <> 'PISTOL'");

                    b.ToTable("weapon_models", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_weapon_models_attributes", "kind = 'PISTOL' OR (side IS NOT NULL AND handedness IS NOT NULL AND size IS NOT NULL)");

                            t.HasCheckConstraint("ck_weapon_models_handedness", "handedness IS NULL OR handedness IN ('RIGHT', 'LEFT')");

                            t.HasCheckConstraint("ck_weapon_models_kind", "kind IN ('TRABUCO', 'ARCABUZ', 'PISTOL')");

                            t.HasCheckConstraint("ck_weapon_models_label_not_blank", "btrim(label) <> ''");

                            t.HasCheckConstraint("ck_weapon_models_pistol_not_rentable", "NOT (kind = 'PISTOL' AND rentable)");

                            t.HasCheckConstraint("ck_weapon_models_side", "side IS NULL OR side IN ('MOORISH', 'CHRISTIAN')");

                            t.HasCheckConstraint("ck_weapon_models_size", "size IS NULL OR size IN ('NORMAL', 'SMALL')");
                        });
                });

            modelBuilder.Entity("PolvorApp.SharedKernel.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid?>("ComparsaId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparsa_id");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_entries_occurred_at");

                    b.HasIndex("ActorUserId", "OccurredAt")
                        .HasDatabaseName("ix_audit_entries_actor_user_id_occurred_at")
                        .HasFilter("actor_user_id IS NOT NULL");

                    b.HasIndex("ComparsaId", "OccurredAt")
                        .HasDatabaseName("ix_audit_entries_comparsa_id_occurred_at")
                        .HasFilter("comparsa_id IS NOT NULL");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_entries_entity_type_entity_id");

                    b.ToTable("audit_entries", "audit", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PolvorApp.FederationCatalog.Assignments.FiringChiefAssignment", b =>
                {
                    b.HasOne("PolvorApp.FederationCatalog.Comparsas.Comparsa", null)
                        .WithMany()
                        .HasForeignKey("ComparsaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_firing_chief_assignments_comparsas_comparsa_id");
                });
#pragma warning restore 612, 618
        }
    }
}
