// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PolvorApp.FederationCatalog.Persistence;

#nullable disable

namespace PolvorApp.FederationCatalog.Persistence.Migrations
{
    [DbContext(typeof(FederationCatalogDbContext))]
    partial class FederationCatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PolvorApp.FederationCatalog.Assignments.FiringChiefAssignment", b =>
                {
                    b.Property<Guid>("ComparsaId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparsa_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.HasKey("ComparsaId", "UserId")
                        .HasName("pk_firing_chief_assignments");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_firing_chief_assignments_user_id");

                    b.ToTable("firing_chief_assignments", "catalog");
                });

            modelBuilder.Entity("PolvorApp.FederationCatalog.Comparsas.Comparsa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("name_key")
                        .HasComputedColumnSql("lower(name)", true);

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("side");

                    b.HasKey("Id")
                        .HasName("pk_comparsas");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasDatabaseName("ix_comparsas_name_key");

                    b.ToTable("comparsas", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_comparsas_logo_complete", "(logo_id IS NULL AND logo_object_key IS NULL AND logo_width IS NULL AND logo_height IS NULL AND logo_size_bytes IS NULL AND logo_uploaded_at IS NULL) OR (logo_id IS NOT NULL AND logo_object_key IS NOT NULL AND logo_width IS NOT NULL AND logo_height IS NOT NULL AND logo_size_bytes IS NOT NULL AND logo_uploaded_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_comparsas_logo_key", "logo_object_key IS NULL OR logo_object_key = 'catalog/logos/' || replace(logo_id::text, '-', '') || '.png'");

                            t.HasCheckConstraint("ck_comparsas_logo_size", "logo_id IS NULL OR (logo_width > 0 AND logo_height > 0 AND logo_size_bytes > 0)");

                            t.HasCheckConstraint("ck_comparsas_name_not_blank", "btrim(name) <> ''");

                            t.HasCheckConstraint("ck_comparsas_side", "side IN ('MOORISH', 'CHRISTIAN')");
                        });
                });

            modelBuilder.Entity("PolvorApp.FederationCatalog.Logos.FederationSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("CloseReminderLeadDays")
                        .HasColumnType("integer")
                        .HasColumnName("close_reminder_lead_days");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("contact_email");

                    b.Property<int>("MilestoneLeadDays")
                        .HasColumnType("integer")
                        .HasColumnName("milestone_lead_days");

                    b.Property<string>("OfficialNameCa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("official_name_ca");

                    b.Property<string>("OfficialNameEs")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("official_name_es");

                    b.Property<string>("ReplyTo")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("reply_to");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("sender_name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("short_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_federation_settings");

                    b.ToTable("federation_settings", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_federation_settings_close_reminder_lead_days", "close_reminder_lead_days BETWEEN 2 AND 14");

                            t.HasCheckConstraint("ck_federation_settings_logo_complete", "(logo_id IS NULL AND logo_object_key IS NULL AND logo_width IS NULL AND logo_height IS NULL AND logo_size_bytes IS NULL AND logo_uploaded_at IS NULL) OR (logo_id IS NOT NULL AND logo_object_key IS NOT NULL AND logo_width IS NOT NULL AND logo_height IS NOT NULL AND logo_size_bytes IS NOT NULL AND logo_uploaded_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_federation_settings_logo_key", "logo_object_key IS NULL OR logo_object_key = 'catalog/logos/' || replace(logo_id::text, '-', '') || '.png'");

                            t.HasCheckConstraint("ck_federation_settings_logo_size", "logo_id IS NULL OR (logo_width > 0 AND logo_height > 0 AND logo_size_bytes > 0)");

                            t.HasCheckConstraint("ck_federation_settings_milestone_lead_days", "milestone_lead_days BETWEEN 1 AND 14");

                            t.HasCheckConstraint("ck_federation_settings_names_not_blank", "btrim(official_name_es) <> '' AND btrim(official_name_ca) <> '' AND btrim(short_name) <> '' AND btrim(sender_name) <> ''");

                            t.HasCheckConstraint("ck_federation_settings_sender_name", "sender_name !~ '[[:cntrl:]<>\"@]'");

                            t.HasCheckConstraint("ck_federation_settings_single", "id = 1");

                            t.HasCheckConstraint("ck_federation_settings_website", "website IS NULL OR website LIKE 'https://%'");
                        });
                });

            modelBuilder.Entity("PolvorApp.FederationCatalog.WeaponModels.WeaponModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Handedness")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("handedness");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<string>("LabelKey")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("label_key")
                        .HasComputedColumnSql("lower(label)", true);

                    b.Property<bool>("Rentable")
                        .HasColumnType("boolean")
                        .HasColumnName("rentable");

                    b.Property<string>("Side")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("side");

                    b.Property<string>("Size")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("size");

                    b.HasKey("Id")
                        .HasName("pk_weapon_models");

                    b.HasIndex("LabelKey")
                        .IsUnique()
                        .HasDatabaseName("ix_weapon_models_label_key");

                    b.HasIndex("Kind", "Side", "Handedness", "Size")
                        .IsUnique()
                        .HasDatabaseName("ix_weapon_models_combination")
                        .HasFilter("kind <> 'PISTOL'");

                    b.ToTable("weapon_models", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_weapon_models_attributes", "kind = 'PISTOL' OR (side IS NOT NULL AND handedness IS NOT NULL AND size IS NOT NULL)");

                            t.HasCheckConstraint("ck_weapon_models_handedness", "handedness IS NULL OR handedness IN ('RIGHT', 'LEFT')");

                            t.HasCheckConstraint("ck_weapon_models_kind", "kind IN ('TRABUCO', 'ARCABUZ', 'PISTOL')");

                            t.HasCheckConstraint("ck_weapon_models_label_not_blank", "btrim(label) <> ''");

                            t.HasCheckConstraint("ck_weapon_models_side", "side IS NULL OR side IN ('MOORISH', 'CHRISTIAN')");

                            t.HasCheckConstraint("ck_weapon_models_size", "size IS NULL OR size IN ('NORMAL', 'SMALL')");
                        });
                });

            modelBuilder.Entity("PolvorApp.SharedKernel.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid?>("ComparsaId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparsa_id");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("OccurredAt", "Id")
                        .HasDatabaseName("ix_audit_entries_occurred_at_id");

                    b.HasIndex("Action", "OccurredAt", "Id")
                        .HasDatabaseName("ix_audit_entries_action_occurred_at_id");

                    b.HasIndex("ActorUserId", "OccurredAt", "Id")
                        .HasDatabaseName("ix_audit_entries_actor_user_id_occurred_at_id")
                        .HasFilter("actor_user_id IS NOT NULL");

                    b.HasIndex("ComparsaId", "OccurredAt", "Id")
                        .HasDatabaseName("ix_audit_entries_comparsa_id_occurred_at_id")
                        .HasFilter("comparsa_id IS NOT NULL");

                    b.HasIndex("EntityType", "EntityId", "OccurredAt", "Id")
                        .HasDatabaseName("ix_audit_entries_entity_type_entity_id_occurred_at_id");

                    b.ToTable("audit_entries", "audit", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PolvorApp.FederationCatalog.Assignments.FiringChiefAssignment", b =>
                {
                    b.HasOne("PolvorApp.FederationCatalog.Comparsas.Comparsa", null)
                        .WithMany()
                        .HasForeignKey("ComparsaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_firing_chief_assignments_comparsas_comparsa_id");
                });

            modelBuilder.Entity("PolvorApp.FederationCatalog.Comparsas.Comparsa", b =>
                {
                    b.OwnsOne("PolvorApp.FederationCatalog.Logos.ComparsaLogo", "Logo", b1 =>
                        {
                            b1.Property<Guid>("ComparsaId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Height")
                                .HasColumnType("integer")
                                .HasColumnName("logo_height");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("logo_id");

                            b1.Property<string>("ObjectKey")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("logo_object_key");

                            b1.Property<int>("SizeBytes")
                                .HasColumnType("integer")
                                .HasColumnName("logo_size_bytes");

                            b1.Property<DateTimeOffset>("UploadedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("logo_uploaded_at");

                            b1.Property<int>("Width")
                                .HasColumnType("integer")
                                .HasColumnName("logo_width");

                            b1.HasKey("ComparsaId");

                            b1.HasIndex("ObjectKey")
                                .IsUnique()
                                .HasDatabaseName("ix_comparsas_logo_object_key")
                                .HasFilter("logo_object_key IS NOT NULL");

                            b1.ToTable("comparsas", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ComparsaId")
                                .HasConstraintName("fk_comparsas_comparsas_id");
                        });

                    b.Navigation("Logo");
                });

            modelBuilder.Entity("PolvorApp.FederationCatalog.Logos.FederationSettings", b =>
                {
                    b.OwnsOne("PolvorApp.FederationCatalog.Logos.ComparsaLogo", "Logo", b1 =>
                        {
                            b1.Property<int>("FederationSettingsId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<int>("Height")
                                .HasColumnType("integer")
                                .HasColumnName("logo_height");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("logo_id");

                            b1.Property<string>("ObjectKey")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("logo_object_key");

                            b1.Property<int>("SizeBytes")
                                .HasColumnType("integer")
                                .HasColumnName("logo_size_bytes");

                            b1.Property<DateTimeOffset>("UploadedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("logo_uploaded_at");

                            b1.Property<int>("Width")
                                .HasColumnType("integer")
                                .HasColumnName("logo_width");

                            b1.HasKey("FederationSettingsId");

                            b1.ToTable("federation_settings", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("FederationSettingsId")
                                .HasConstraintName("fk_federation_settings_federation_settings_id");
                        });

                    b.Navigation("Logo");
                });
#pragma warning restore 612, 618
        }
    }
}
