// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PolvorApp.FestivalEditions.Persistence;

#nullable disable

namespace PolvorApp.FestivalEditions.Persistence.Migrations
{
    [DbContext(typeof(FestivalEditionsDbContext))]
    [Migration("20261004003208_MapNotificationOutbox")]
    partial class MapNotificationOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("editions")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PolvorApp.FestivalEditions.Editions.CalendarMilestone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<bool>("Notify")
                        .HasColumnType("boolean")
                        .HasColumnName("notify");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_calendar_milestones");

                    b.HasIndex("EditionId", "Date")
                        .HasDatabaseName("ix_calendar_milestones_edition_id_date");

                    b.ToTable("calendar_milestones", "editions", t =>
                        {
                            t.HasCheckConstraint("ck_calendar_milestones_title_not_blank", "btrim(title) <> ''");
                        });
                });

            modelBuilder.Entity("PolvorApp.FestivalEditions.Editions.EditionWeaponModel", b =>
                {
                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<Guid>("WeaponModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("weapon_model_id");

                    b.HasKey("EditionId", "WeaponModelId")
                        .HasName("pk_edition_weapon_models");

                    b.HasIndex("WeaponModelId")
                        .HasDatabaseName("ix_edition_weapon_models_weapon_model_id");

                    b.ToTable("edition_weapon_models", "editions");
                });

            modelBuilder.Entity("PolvorApp.FestivalEditions.Editions.FestivalEdition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("CapsBox")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("caps_box");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("FestivalEndsOn")
                        .HasColumnType("date")
                        .HasColumnName("festival_ends_on");

                    b.Property<DateOnly>("FestivalStartsOn")
                        .HasColumnType("date")
                        .HasColumnName("festival_starts_on");

                    b.Property<decimal?>("FlaskRental")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("flask_rental");

                    b.Property<DateOnly?>("OrdersCloseOn")
                        .HasColumnType("date")
                        .HasColumnName("orders_close_on");

                    b.Property<bool>("OrdersOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("orders_open");

                    b.Property<DateOnly?>("OrdersOpenOn")
                        .HasColumnType("date")
                        .HasColumnName("orders_open_on");

                    b.Property<decimal?>("PowderPerKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("powder_per_kg");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<decimal?>("WeaponRental")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("weapon_rental");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_festival_editions");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasDatabaseName("ux_festival_editions_in_progress")
                        .HasFilter("status = 'IN_PROGRESS'");

                    b.HasIndex("Year")
                        .IsUnique()
                        .HasDatabaseName("ix_festival_editions_year");

                    b.ToTable("festival_editions", "editions", t =>
                        {
                            t.HasCheckConstraint("ck_festival_editions_caps_box", "caps_box IS NULL OR caps_box >= 0");

                            t.HasCheckConstraint("ck_festival_editions_festival_dates", "festival_ends_on >= festival_starts_on");

                            t.HasCheckConstraint("ck_festival_editions_flask_rental", "flask_rental IS NULL OR flask_rental >= 0");

                            t.HasCheckConstraint("ck_festival_editions_orders_open_in_progress", "NOT orders_open OR status = 'IN_PROGRESS'");

                            t.HasCheckConstraint("ck_festival_editions_orders_window", "orders_open_on IS NULL OR orders_close_on IS NULL OR orders_close_on >= orders_open_on");

                            t.HasCheckConstraint("ck_festival_editions_powder_per_kg", "powder_per_kg IS NULL OR powder_per_kg >= 0");

                            t.HasCheckConstraint("ck_festival_editions_status", "status IN ('DRAFT', 'IN_PROGRESS', 'CLOSED')");

                            t.HasCheckConstraint("ck_festival_editions_weapon_rental", "weapon_rental IS NULL OR weapon_rental >= 0");

                            t.HasCheckConstraint("ck_festival_editions_year", "year BETWEEN 2000 AND 2100");
                        });
                });

            modelBuilder.Entity("PolvorApp.Notifications.Contracts.NotificationEventEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ComparsaId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparsa_id");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notification_events");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_notification_events_pending")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("notification_events", "notifications", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PolvorApp.SharedKernel.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid?>("ComparsaId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparsa_id");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_entries_occurred_at");

                    b.HasIndex("ActorUserId", "OccurredAt")
                        .HasDatabaseName("ix_audit_entries_actor_user_id_occurred_at")
                        .HasFilter("actor_user_id IS NOT NULL");

                    b.HasIndex("ComparsaId", "OccurredAt")
                        .HasDatabaseName("ix_audit_entries_comparsa_id_occurred_at")
                        .HasFilter("comparsa_id IS NOT NULL");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_entries_entity_type_entity_id");

                    b.ToTable("audit_entries", "audit", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PolvorApp.FestivalEditions.Editions.CalendarMilestone", b =>
                {
                    b.HasOne("PolvorApp.FestivalEditions.Editions.FestivalEdition", null)
                        .WithMany()
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_milestones_festival_editions_edition_id");
                });

            modelBuilder.Entity("PolvorApp.FestivalEditions.Editions.EditionWeaponModel", b =>
                {
                    b.HasOne("PolvorApp.FestivalEditions.Editions.FestivalEdition", null)
                        .WithMany()
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_edition_weapon_models_festival_editions_edition_id");
                });
#pragma warning restore 612, 618
        }
    }
}
