// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PolvorApp.ArquebusierRegistry.Persistence;

#nullable disable

namespace PolvorApp.ArquebusierRegistry.Persistence.Migrations
{
    [DbContext(typeof(ArquebusierRegistryDbContext))]
    partial class ArquebusierRegistryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("registry")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PolvorApp.ArquebusierRegistry.Arquebusiers.Arquebusier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<Guid>("ComparsaId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparsa_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<int>("FederationId")
                        .HasColumnType("integer")
                        .HasColumnName("federation_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateOnly?>("LicenseExpiresOn")
                        .HasColumnType("date")
                        .HasColumnName("license_expires_on");

                    b.Property<DateOnly?>("LicenseIssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("license_issued_on");

                    b.Property<bool>("LicensePending")
                        .HasColumnType("boolean")
                        .HasColumnName("license_pending");

                    b.Property<string>("LicenseType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("license_type");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("national_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("TrainingCompletedOn")
                        .HasColumnType("date")
                        .HasColumnName("training_completed_on");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_arquebusiers");

                    b.HasIndex("ComparsaId")
                        .HasDatabaseName("ix_arquebusiers_comparsa_id");

                    b.HasIndex("FederationId")
                        .IsUnique()
                        .HasDatabaseName("ix_arquebusiers_federation_id");

                    b.HasIndex("NationalId")
                        .IsUnique()
                        .HasDatabaseName("ix_arquebusiers_national_id");

                    b.ToTable("arquebusiers", "registry", t =>
                        {
                            t.HasCheckConstraint("ck_arquebusiers_birth_date", "birth_date >= DATE '1900-01-01'");

                            t.HasCheckConstraint("ck_arquebusiers_email", "email = lower(email) AND email = btrim(email) AND email <> ''");

                            t.HasCheckConstraint("ck_arquebusiers_federation_id", "federation_id BETWEEN 1 AND 999999999");

                            t.HasCheckConstraint("ck_arquebusiers_first_name", "btrim(first_name) <> '' AND first_name = btrim(first_name) AND first_name !~ '[[:cntrl:]]'");

                            t.HasCheckConstraint("ck_arquebusiers_gender", "gender IN ('MALE', 'FEMALE', 'UNSPECIFIED')");

                            t.HasCheckConstraint("ck_arquebusiers_last_name", "btrim(last_name) <> '' AND last_name = btrim(last_name) AND last_name !~ '[[:cntrl:]]'");

                            t.HasCheckConstraint("ck_arquebusiers_license", "(license_type IS NULL AND NOT license_pending AND license_issued_on IS NULL AND license_expires_on IS NULL) OR (license_type IS NOT NULL AND license_pending AND license_issued_on IS NULL AND license_expires_on IS NULL) OR (license_type IS NOT NULL AND NOT license_pending AND license_issued_on IS NOT NULL AND license_expires_on IS NOT NULL AND license_expires_on > license_issued_on)");

                            t.HasCheckConstraint("ck_arquebusiers_license_type", "license_type IS NULL OR license_type IN ('AE', 'A_PROF')");

                            t.HasCheckConstraint("ck_arquebusiers_national_id", "national_id ~ '^([0-9]{8}|[XYZ][0-9]{7})[A-Z]$'");

                            t.HasCheckConstraint("ck_arquebusiers_phone", "phone ~ '^[+]?[0-9 ]+$'");

                            t.HasCheckConstraint("ck_arquebusiers_status", "status IN ('ACTIVE', 'RESERVE')");
                        });
                });

            modelBuilder.Entity("PolvorApp.ArquebusierRegistry.OwnedWeapons.OwnedWeapon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArquebusierId")
                        .HasColumnType("uuid")
                        .HasColumnName("arquebusier_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OwnershipGuideNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ownership_guide_number");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WeaponModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("weapon_model_id");

                    b.Property<string>("WeaponNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("weapon_number");

                    b.HasKey("Id")
                        .HasName("pk_owned_weapons");

                    b.HasIndex("ArquebusierId")
                        .HasDatabaseName("ix_owned_weapons_arquebusier_id");

                    b.HasIndex("OwnershipGuideNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_owned_weapons_ownership_guide_number");

                    b.HasIndex("WeaponModelId")
                        .HasDatabaseName("ix_owned_weapons_weapon_model_id");

                    b.ToTable("owned_weapons", "registry", t =>
                        {
                            t.HasCheckConstraint("ck_owned_weapons_ownership_guide_number", "btrim(ownership_guide_number) <> '' AND ownership_guide_number = btrim(ownership_guide_number) AND ownership_guide_number COLLATE \"C\" = upper(ownership_guide_number COLLATE \"C\")");

                            t.HasCheckConstraint("ck_owned_weapons_weapon_number", "btrim(weapon_number) <> '' AND weapon_number = btrim(weapon_number)");
                        });
                });

            modelBuilder.Entity("PolvorApp.SharedKernel.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid?>("ComparsaId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparsa_id");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_entries_occurred_at");

                    b.HasIndex("ActorUserId", "OccurredAt")
                        .HasDatabaseName("ix_audit_entries_actor_user_id_occurred_at")
                        .HasFilter("actor_user_id IS NOT NULL");

                    b.HasIndex("ComparsaId", "OccurredAt")
                        .HasDatabaseName("ix_audit_entries_comparsa_id_occurred_at")
                        .HasFilter("comparsa_id IS NOT NULL");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_entries_entity_type_entity_id");

                    b.ToTable("audit_entries", "audit", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PolvorApp.ArquebusierRegistry.OwnedWeapons.OwnedWeapon", b =>
                {
                    b.HasOne("PolvorApp.ArquebusierRegistry.Arquebusiers.Arquebusier", null)
                        .WithMany("OwnedWeapons")
                        .HasForeignKey("ArquebusierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_owned_weapons_arquebusiers_arquebusier_id");
                });

            modelBuilder.Entity("PolvorApp.ArquebusierRegistry.Arquebusiers.Arquebusier", b =>
                {
                    b.Navigation("OwnedWeapons");
                });
#pragma warning restore 612, 618
        }
    }
}
