// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PolvorApp.Distribution.Persistence;

#nullable disable

namespace PolvorApp.Distribution.Persistence.Migrations
{
    [DbContext(typeof(DistributionDbContext))]
    [Migration("20261009141132_AddHandovers")]
    partial class AddHandovers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("distribution")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PolvorApp.Distribution.Days.DistributionDay", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_distributions");

                    b.HasIndex("EditionId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ux_distributions_edition_type");

                    b.ToTable("distributions", "distribution", t =>
                        {
                            t.HasCheckConstraint("ck_distributions_location_not_blank", "btrim(location) <> ''");

                            t.HasCheckConstraint("ck_distributions_type", "type IN ('POWDER', 'WEAPONS')");
                        });
                });

            modelBuilder.Entity("PolvorApp.Distribution.Days.DistributionSlot", b =>
                {
                    b.Property<Guid>("DistributionId")
                        .HasColumnType("uuid")
                        .HasColumnName("distribution_id");

                    b.Property<Guid>("ComparsaId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparsa_id");

                    b.Property<TimeOnly>("StartsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("DistributionId", "ComparsaId")
                        .HasName("pk_distribution_slots");

                    b.HasIndex("ComparsaId")
                        .HasDatabaseName("ix_distribution_slots_comparsa_id");

                    b.ToTable("distribution_slots", "distribution");
                });

            modelBuilder.Entity("PolvorApp.Distribution.Handovers.Handover", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<string>("CollectedBy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("collected_by");

                    b.Property<Guid?>("CollectorEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("collector_entry_id");

                    b.Property<Guid>("DistributionId")
                        .HasColumnType("uuid")
                        .HasColumnName("distribution_id");

                    b.Property<int>("DistributionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("distribution_number");

                    b.Property<Guid>("HolderEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("holder_entry_id");

                    b.Property<short>("PowderKg")
                        .HasColumnType("smallint")
                        .HasColumnName("powder_kg");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("RentalFlaskNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rental_flask_number");

                    b.Property<string>("Traceability1")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("traceability1");

                    b.Property<string>("Traceability2")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("traceability2");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_handovers");

                    b.HasIndex("CollectorEntryId")
                        .HasDatabaseName("ix_handovers_collector_entry_id")
                        .HasFilter("collector_entry_id IS NOT NULL");

                    b.HasIndex("HolderEntryId")
                        .HasDatabaseName("ix_handovers_holder_entry_id");

                    b.HasIndex("DistributionId", "HolderEntryId")
                        .IsUnique()
                        .HasDatabaseName("ux_handovers_distribution_holder");

                    b.ToTable("handovers", "distribution", t =>
                        {
                            t.HasCheckConstraint("ck_handovers_collected_by", "collected_by IN ('HOLDER', 'PROXY')");

                            t.HasCheckConstraint("ck_handovers_collector", "collected_by = 'PROXY' OR collector_entry_id IS NULL");

                            t.HasCheckConstraint("ck_handovers_distribution_number", "distribution_number > 0");

                            t.HasCheckConstraint("ck_handovers_not_holder", "collector_entry_id <> holder_entry_id");

                            t.HasCheckConstraint("ck_handovers_powder_kg", "powder_kg BETWEEN 1 AND 2");

                            t.HasCheckConstraint("ck_handovers_texts_not_blank", "(rental_flask_number IS NULL OR btrim(rental_flask_number) <> '') AND (traceability1 IS NULL OR btrim(traceability1) <> '') AND (traceability2 IS NULL OR btrim(traceability2) <> '')");
                        });
                });

            modelBuilder.Entity("PolvorApp.Distribution.Proxies.PickupProxy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ComparsaId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparsa_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<Guid>("HolderEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("holder_entry_id");

                    b.Property<Guid>("ProxyEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("proxy_entry_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_pickup_proxies");

                    b.HasIndex("ComparsaId")
                        .HasDatabaseName("ix_pickup_proxies_comparsa_id");

                    b.HasIndex("ProxyEntryId")
                        .HasDatabaseName("ix_pickup_proxies_proxy_entry_id");

                    b.HasIndex("EditionId", "ComparsaId")
                        .HasDatabaseName("ix_pickup_proxies_edition_id_comparsa_id");

                    b.HasIndex("HolderEntryId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ux_pickup_proxies_holder_type");

                    b.ToTable("pickup_proxies", "distribution", t =>
                        {
                            t.HasCheckConstraint("ck_pickup_proxies_not_holder", "holder_entry_id <> proxy_entry_id");

                            t.HasCheckConstraint("ck_pickup_proxies_type", "type IN ('POWDER', 'WEAPONS')");
                        });
                });

            modelBuilder.Entity("PolvorApp.SharedKernel.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid?>("ComparsaId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparsa_id");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("OccurredAt", "Id")
                        .HasDatabaseName("ix_audit_entries_occurred_at_id");

                    b.HasIndex("Action", "OccurredAt", "Id")
                        .HasDatabaseName("ix_audit_entries_action_occurred_at_id");

                    b.HasIndex("ActorUserId", "OccurredAt", "Id")
                        .HasDatabaseName("ix_audit_entries_actor_user_id_occurred_at_id")
                        .HasFilter("actor_user_id IS NOT NULL");

                    b.HasIndex("ComparsaId", "OccurredAt", "Id")
                        .HasDatabaseName("ix_audit_entries_comparsa_id_occurred_at_id")
                        .HasFilter("comparsa_id IS NOT NULL");

                    b.HasIndex("EntityType", "EntityId", "OccurredAt", "Id")
                        .HasDatabaseName("ix_audit_entries_entity_type_entity_id_occurred_at_id");

                    b.ToTable("audit_entries", "audit", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PolvorApp.Distribution.Days.DistributionSlot", b =>
                {
                    b.HasOne("PolvorApp.Distribution.Days.DistributionDay", null)
                        .WithMany("Slots")
                        .HasForeignKey("DistributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_distribution_slots_distributions_distribution_id");
                });

            modelBuilder.Entity("PolvorApp.Distribution.Handovers.Handover", b =>
                {
                    b.HasOne("PolvorApp.Distribution.Days.DistributionDay", null)
                        .WithMany()
                        .HasForeignKey("DistributionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_handovers_distribution");
                });

            modelBuilder.Entity("PolvorApp.Distribution.Days.DistributionDay", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
