// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PolvorApp.Distribution.Persistence;

#nullable disable

namespace PolvorApp.Distribution.Persistence.Migrations
{
    [DbContext(typeof(DistributionDbContext))]
    partial class DistributionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("distribution")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PolvorApp.Distribution.Days.DistributionDay", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_distributions");

                    b.HasIndex("EditionId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ux_distributions_edition_type");

                    b.ToTable("distributions", "distribution", t =>
                        {
                            t.HasCheckConstraint("ck_distributions_location_not_blank", "btrim(location) <> ''");

                            t.HasCheckConstraint("ck_distributions_type", "type IN ('POWDER', 'WEAPONS')");
                        });
                });

            modelBuilder.Entity("PolvorApp.Distribution.Days.DistributionSlot", b =>
                {
                    b.Property<Guid>("DistributionId")
                        .HasColumnType("uuid")
                        .HasColumnName("distribution_id");

                    b.Property<Guid>("ComparsaId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparsa_id");

                    b.Property<TimeOnly>("StartsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("DistributionId", "ComparsaId")
                        .HasName("pk_distribution_slots");

                    b.HasIndex("ComparsaId")
                        .HasDatabaseName("ix_distribution_slots_comparsa_id");

                    b.ToTable("distribution_slots", "distribution");
                });

            modelBuilder.Entity("PolvorApp.Distribution.Proxies.PickupProxy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ComparsaId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparsa_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<Guid>("HolderEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("holder_entry_id");

                    b.Property<Guid>("ProxyEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("proxy_entry_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_pickup_proxies");

                    b.HasIndex("ComparsaId")
                        .HasDatabaseName("ix_pickup_proxies_comparsa_id");

                    b.HasIndex("ProxyEntryId")
                        .HasDatabaseName("ix_pickup_proxies_proxy_entry_id");

                    b.HasIndex("EditionId", "ComparsaId")
                        .HasDatabaseName("ix_pickup_proxies_edition_id_comparsa_id");

                    b.HasIndex("HolderEntryId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ux_pickup_proxies_holder_type");

                    b.ToTable("pickup_proxies", "distribution", t =>
                        {
                            t.HasCheckConstraint("ck_pickup_proxies_not_holder", "holder_entry_id <> proxy_entry_id");

                            t.HasCheckConstraint("ck_pickup_proxies_type", "type IN ('POWDER', 'WEAPONS')");
                        });
                });

            modelBuilder.Entity("PolvorApp.SharedKernel.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid?>("ComparsaId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparsa_id");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_entries_occurred_at");

                    b.HasIndex("ActorUserId", "OccurredAt")
                        .HasDatabaseName("ix_audit_entries_actor_user_id_occurred_at")
                        .HasFilter("actor_user_id IS NOT NULL");

                    b.HasIndex("ComparsaId", "OccurredAt")
                        .HasDatabaseName("ix_audit_entries_comparsa_id_occurred_at")
                        .HasFilter("comparsa_id IS NOT NULL");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_entries_entity_type_entity_id");

                    b.ToTable("audit_entries", "audit", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PolvorApp.Distribution.Days.DistributionSlot", b =>
                {
                    b.HasOne("PolvorApp.Distribution.Days.DistributionDay", null)
                        .WithMany("Slots")
                        .HasForeignKey("DistributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_distribution_slots_distributions_distribution_id");
                });

            modelBuilder.Entity("PolvorApp.Distribution.Days.DistributionDay", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
