using System.Buffers.Binary;
using System.Security.Cryptography;

namespace PolvorApp.IdentityAccess.Security;

/// <summary>
/// RFC 6238 TOTP (HMAC-SHA1, 30-second step, 6 digits) as authenticator apps implement it. Kept
/// here, instead of Identity's internal implementation, so the matched time step is known and a
/// code cannot be replayed (design D5).
/// </summary>
internal static class Totp
{
    public const int Digits = 6;
    public static readonly TimeSpan Step = TimeSpan.FromSeconds(30);

    /// <summary>Accepted clock drift in steps on either side (±30 s).</summary>
    public const int Tolerance = 1;

    private const int Modulo = 1_000_000;

    public static long StepAt(DateTimeOffset time) => time.ToUnixTimeSeconds() / (long)Step.TotalSeconds;

    public static string Compute(byte[] key, long step)
    {
        ArgumentNullException.ThrowIfNull(key);
        Span<byte> counter = stackalloc byte[sizeof(long)];
        BinaryPrimitives.WriteInt64BigEndian(counter, step);
        Span<byte> hash = stackalloc byte[HMACSHA1.HashSizeInBytes];
#pragma warning disable CA5350 // HMAC-SHA1 is what RFC 6238 authenticator apps use; not used as a general hash.
        HMACSHA1.HashData(key, counter, hash);
#pragma warning restore CA5350
        var offset = hash[^1] & 0x0F;
        var binary = ((hash[offset] & 0x7F) << 24) | (hash[offset + 1] << 16) | (hash[offset + 2] << 8) | hash[offset + 3];
        return (binary % Modulo).ToString($"D{Digits}", System.Globalization.CultureInfo.InvariantCulture);
    }

    /// <summary>The step whose code equals <paramref name="code"/> within the tolerance, if any.</summary>
    public static long? MatchStep(byte[] key, string code, DateTimeOffset now)
    {
        var normalized = Normalize(code);
        if (normalized is null)
        {
            return null;
        }

        var current = StepAt(now);
        for (var step = current - Tolerance; step <= current + Tolerance; step++)
        {
            if (CryptographicOperations.FixedTimeEquals(
                System.Text.Encoding.ASCII.GetBytes(Compute(key, step)), System.Text.Encoding.ASCII.GetBytes(normalized)))
            {
                return step;
            }
        }

        return null;
    }

    /// <summary>Removes spaces and dashes users type; null unless exactly six digits remain.</summary>
    public static string? Normalize(string? code)
    {
        if (code is null)
        {
            return null;
        }

        var digits = new string(code.Where(c => c is not (' ' or '-')).ToArray());
        return digits.Length == Digits && digits.All(char.IsAsciiDigit) ? digits : null;
    }

    /// <summary>Decodes an RFC 4648 Base32 key as generated by Identity (upper case, no padding).</summary>
    public static byte[] DecodeBase32(string key)
    {
        ArgumentNullException.ThrowIfNull(key);
        const string alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
        var clean = key.TrimEnd('=').Replace(" ", string.Empty, StringComparison.Ordinal).ToUpperInvariant();
        var output = new byte[clean.Length * 5 / 8];
        int buffer = 0, bits = 0, index = 0;
        foreach (var c in clean)
        {
            var value = alphabet.IndexOf(c, StringComparison.Ordinal);
            if (value < 0)
            {
                throw new FormatException("The authenticator key is not valid Base32.");
            }

            buffer = (buffer << 5) | value;
            bits += 5;
            if (bits >= 8)
            {
                output[index++] = (byte)(buffer >> (bits - 8));
                bits -= 8;
            }
        }

        return output;
    }
}
