// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PolvorApp.ComparsaOrders.Persistence;

#nullable disable

namespace PolvorApp.ComparsaOrders.Persistence.Migrations
{
    [DbContext(typeof(ComparsaOrdersDbContext))]
    partial class ComparsaOrdersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("orders")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PolvorApp.ComparsaOrders.Entries.EditionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArquebusierId")
                        .HasColumnType("uuid")
                        .HasColumnName("arquebusier_id");

                    b.Property<short>("CapsBoxes")
                        .HasColumnType("smallint")
                        .HasColumnName("caps_boxes");

                    b.Property<string>("CapsType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("caps_type");

                    b.Property<DateTimeOffset>("CopiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("copied_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<DateTimeOffset?>("ErasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("erased_at");

                    b.Property<int?>("FederationId")
                        .HasColumnType("integer")
                        .HasColumnName("federation_id");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Flask")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("flask");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("NationalId")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("national_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("OwnedWeaponGuideNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("owned_weapon_guide_number");

                    b.Property<Guid?>("OwnedWeaponId")
                        .HasColumnType("uuid")
                        .HasColumnName("owned_weapon_id");

                    b.Property<Guid?>("OwnedWeaponModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("owned_weapon_model_id");

                    b.Property<string>("OwnedWeaponNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("owned_weapon_number");

                    b.Property<short>("PowderKg")
                        .HasColumnType("smallint")
                        .HasColumnName("powder_kg");

                    b.Property<Guid?>("RentalWeaponModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("rental_weapon_model_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("WeaponSource")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("weapon_source");

                    b.HasKey("Id")
                        .HasName("pk_edition_entries");

                    b.HasIndex("ArquebusierId")
                        .HasDatabaseName("ix_edition_entries_arquebusier_id")
                        .HasFilter("arquebusier_id IS NOT NULL");

                    b.HasIndex("NationalId")
                        .HasDatabaseName("ix_edition_entries_national_id")
                        .HasFilter("national_id IS NOT NULL");

                    b.HasIndex("OwnedWeaponId")
                        .HasDatabaseName("ix_edition_entries_owned_weapon_id")
                        .HasFilter("owned_weapon_id IS NOT NULL");

                    b.HasIndex("OwnedWeaponModelId")
                        .HasDatabaseName("ix_edition_entries_owned_weapon_model_id")
                        .HasFilter("owned_weapon_model_id IS NOT NULL");

                    b.HasIndex("RentalWeaponModelId")
                        .HasDatabaseName("ix_edition_entries_rental_weapon_model_id")
                        .HasFilter("rental_weapon_model_id IS NOT NULL");

                    b.HasIndex("EditionId", "ArquebusierId")
                        .IsUnique()
                        .HasDatabaseName("ux_edition_entries_edition_arquebusier")
                        .HasFilter("arquebusier_id IS NOT NULL");

                    b.HasIndex("OrderId", "EditionId")
                        .HasDatabaseName("ix_edition_entries_order_id_edition_id");

                    b.ToTable("edition_entries", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_edition_entries_caps_boxes", "caps_boxes BETWEEN 0 AND 99");

                            t.HasCheckConstraint("ck_edition_entries_caps_type", "(caps_boxes = 0) = (caps_type IS NULL)");

                            t.HasCheckConstraint("ck_edition_entries_caps_type_code", "caps_type IS NULL OR caps_type IN ('NORMAL', 'SMALL')");

                            t.HasCheckConstraint("ck_edition_entries_copy", "arquebusier_id IS NULL OR (first_name IS NOT NULL AND last_name IS NOT NULL AND national_id IS NOT NULL AND federation_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_edition_entries_erased", "erased_at IS NULL OR (arquebusier_id IS NULL AND first_name IS NULL AND last_name IS NULL AND national_id IS NULL AND federation_id IS NULL AND owned_weapon_number IS NULL AND owned_weapon_guide_number IS NULL)");

                            t.HasCheckConstraint("ck_edition_entries_flask", "flask IN ('OWNED', 'RENTAL_1KG', 'RENTAL_2KG', 'NONE')");

                            t.HasCheckConstraint("ck_edition_entries_owned", "weapon_source = 'OWNED' OR (owned_weapon_id IS NULL AND owned_weapon_model_id IS NULL AND owned_weapon_number IS NULL AND owned_weapon_guide_number IS NULL)");

                            t.HasCheckConstraint("ck_edition_entries_powder_kg", "powder_kg BETWEEN 0 AND 2");

                            t.HasCheckConstraint("ck_edition_entries_rental", "(weapon_source = 'RENTAL') = (rental_weapon_model_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_edition_entries_reserve", "status <> 'RESERVE' OR (powder_kg = 0 AND caps_boxes = 0 AND weapon_source = 'NONE' AND flask = 'NONE')");

                            t.HasCheckConstraint("ck_edition_entries_status", "status IN ('ACTIVE', 'RESERVE')");

                            t.HasCheckConstraint("ck_edition_entries_weapon_source", "weapon_source IN ('OWNED', 'RENTAL', 'LOAN', 'NONE')");
                        });
                });

            modelBuilder.Entity("PolvorApp.ComparsaOrders.Loans.WeaponLoan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CopiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("copied_at");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<DateTimeOffset?>("ErasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("erased_at");

                    b.Property<Guid?>("LenderComparsaId")
                        .HasColumnType("uuid")
                        .HasColumnName("lender_comparsa_id");

                    b.Property<string>("LenderFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lender_first_name");

                    b.Property<string>("LenderKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("lender_kind");

                    b.Property<string>("LenderLastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lender_last_name");

                    b.Property<string>("LenderNationalId")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("lender_national_id");

                    b.Property<Guid?>("LenderOwnedWeaponId")
                        .HasColumnType("uuid")
                        .HasColumnName("lender_owned_weapon_id");

                    b.Property<string>("OwnershipGuideNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ownership_guide_number");

                    b.Property<Guid?>("WeaponModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("weapon_model_id");

                    b.Property<string>("WeaponNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("weapon_number");

                    b.HasKey("Id")
                        .HasName("pk_weapon_loans");

                    b.HasIndex("EntryId")
                        .IsUnique()
                        .HasDatabaseName("ix_weapon_loans_entry_id");

                    b.HasIndex("LenderComparsaId")
                        .HasDatabaseName("ix_weapon_loans_lender_comparsa_id")
                        .HasFilter("lender_comparsa_id IS NOT NULL");

                    b.HasIndex("LenderNationalId")
                        .HasDatabaseName("ix_weapon_loans_lender_national_id")
                        .HasFilter("lender_national_id IS NOT NULL");

                    b.HasIndex("LenderOwnedWeaponId")
                        .HasDatabaseName("ix_weapon_loans_lender_owned_weapon_id")
                        .HasFilter("lender_owned_weapon_id IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("LenderOwnedWeaponId"), new[] { "EntryId" });

                    b.HasIndex("WeaponModelId")
                        .HasDatabaseName("ix_weapon_loans_weapon_model_id")
                        .HasFilter("weapon_model_id IS NOT NULL");

                    b.ToTable("weapon_loans", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_weapon_loans_erased", "erased_at IS NULL OR (lender_owned_weapon_id IS NULL AND lender_first_name IS NULL AND lender_last_name IS NULL AND lender_national_id IS NULL AND weapon_number IS NULL AND ownership_guide_number IS NULL)");

                            t.HasCheckConstraint("ck_weapon_loans_external", "lender_kind <> 'EXTERNAL' OR (lender_owned_weapon_id IS NULL AND lender_comparsa_id IS NULL)");

                            t.HasCheckConstraint("ck_weapon_loans_lender_kind", "lender_kind IN ('ARQUEBUSIER', 'EXTERNAL')");

                            t.HasCheckConstraint("ck_weapon_loans_registered", "lender_kind <> 'ARQUEBUSIER' OR lender_comparsa_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("PolvorApp.ComparsaOrders.Orders.ComparsaOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Attested")
                        .HasColumnType("boolean")
                        .HasColumnName("attested");

                    b.Property<Guid>("ComparsaId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparsa_id");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<int>("EditionYear")
                        .HasColumnType("integer")
                        .HasColumnName("edition_year");

                    b.Property<DateTimeOffset>("PreparedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prepared_at");

                    b.Property<Guid>("PreparedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("prepared_by_user_id");

                    b.Property<string>("ReturnReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("return_reason");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<bool>("SubmittedByAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("submitted_by_admin");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by_user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_comparsa_orders");

                    b.HasAlternateKey("Id", "EditionId")
                        .HasName("ak_comparsa_orders_id_edition_id");

                    b.HasIndex("ComparsaId")
                        .HasDatabaseName("ix_comparsa_orders_comparsa_id");

                    b.HasIndex("EditionYear")
                        .HasDatabaseName("ix_comparsa_orders_edition_year");

                    b.HasIndex("EditionId", "ComparsaId")
                        .IsUnique()
                        .HasDatabaseName("ux_comparsa_orders_edition_comparsa");

                    b.ToTable("comparsa_orders", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_comparsa_orders_return_reason", "(status = 'RETURNED') = (return_reason IS NOT NULL) AND (return_reason IS NULL OR btrim(return_reason) <> '')");

                            t.HasCheckConstraint("ck_comparsa_orders_status", "status IN ('DRAFT', 'SUBMITTED', 'RETURNED', 'VALIDATED')");

                            t.HasCheckConstraint("ck_comparsa_orders_submission", "NOT (attested AND submitted_by_admin)");
                        });
                });

            modelBuilder.Entity("PolvorApp.Notifications.Contracts.NotificationEventEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ComparsaId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparsa_id");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("edition_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notification_events");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_notification_events_pending")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("notification_events", "notifications", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PolvorApp.SharedKernel.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid?>("ComparsaId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparsa_id");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_entries_entity_type_entity_id");

                    b.HasIndex("OccurredAt", "Id")
                        .HasDatabaseName("ix_audit_entries_occurred_at_id");

                    b.HasIndex("Action", "OccurredAt", "Id")
                        .HasDatabaseName("ix_audit_entries_action_occurred_at_id");

                    b.HasIndex("ActorUserId", "OccurredAt", "Id")
                        .HasDatabaseName("ix_audit_entries_actor_user_id_occurred_at_id")
                        .HasFilter("actor_user_id IS NOT NULL");

                    b.HasIndex("ComparsaId", "OccurredAt", "Id")
                        .HasDatabaseName("ix_audit_entries_comparsa_id_occurred_at_id")
                        .HasFilter("comparsa_id IS NOT NULL");

                    b.ToTable("audit_entries", "audit", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PolvorApp.ComparsaOrders.Entries.EditionEntry", b =>
                {
                    b.HasOne("PolvorApp.ComparsaOrders.Orders.ComparsaOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId", "EditionId")
                        .HasPrincipalKey("Id", "EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_edition_entries_comparsa_orders_order_id_edition_id");
                });

            modelBuilder.Entity("PolvorApp.ComparsaOrders.Loans.WeaponLoan", b =>
                {
                    b.HasOne("PolvorApp.ComparsaOrders.Entries.EditionEntry", null)
                        .WithOne()
                        .HasForeignKey("PolvorApp.ComparsaOrders.Loans.WeaponLoan", "EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_weapon_loans_edition_entries_entry_id");
                });
#pragma warning restore 612, 618
        }
    }
}
